version: "3.9"
services:
  microservice-account:
    container_name: microservice-account
    build:
      context: ./
      dockerfile: ./microservice-account/Dockerfile
    #image: microservice-account
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DATA_BASE: db_cuenta
      DB_USERNAME: postgres
      DB_PASSWORD: sasa
      CLIENT_URL: microservice-client:8001/api/v1
    networks:
      - neoris
    depends_on:
      - postgres14
    restart: always
  microservice-client:
      container_name: microservice-client
      build:
        context: ./
        dockerfile: ./microservice-client/Dockerfile
      image: microservice-client
      ports:
        - "8001:8001"
      environment:
        PORT: 8001
        DB_HOST: mysql8:3306
        DATA_BASE: db_cliente
        DB_USERNAME: root
        DB_PASSWORD: sasa
        ACCOUNT_URL: microservice-account:8001/api/v1
      networks:
        - neoris
      depends_on:
        - mysql8
      restart: always
  microservice-movement:
    container_name: microservice-movement
    build:
      context: ./
      dockerfile: ./microservice-movement/Dockerfile
    image: microservice-movement
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
      DB_HOST: mongodb:27017
      DATA_BASE: db_movimiento
      DB_USERNAME: mongouser
      DB_PASSWORD: mongopass
      ACCOUNT_URL: microservice-account:8001/api/v1/cuentas
      CLIENT_URL: microservice-client:8001/api/v1/clientes
      BASE_URL:
    networks:
      - neoris
    depends_on:
      - mongodb
    restart: always
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: db_cliente
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - neoris
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: db_cuenta
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - neoris
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: mongouser
      MONGODB_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: db_movimiento
    volumes:
      - data-mongo:/data/db
    restart: always
    networks:
      - neoris

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
  data-mongo:
    name: data-mongo

networks:
  neoris:
    name: neoris